################################# Basic configuration #########################
# Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL = "https://goonline.dev"
title = "Go Online | Web Solutions"
theme = "airspace-hugo"
# Number of posts per page in list view
paginate = "4"
# Post excerpt length
summaryLength = "30"
# Disabled languages
disableLanguages = []
# Short name to enable Disqus comments
disqusShortname = "" # Get your shortname from here: https://disqus.com/profile/signup/
# Measurement ID (G-XXXXXXX) to enable Google Analytics
googleAnalytics = ""


################################# Output formats ##############################
# Documentation: https://gohugo.io/templates/output-formats/#customizing-output-formats

[outputs]
home = [ "HTML" ]


################################# Markup ######################################
# Documentation: https://gohugo.io/getting-started/configuration-markup

[markup.goldmark.renderer]
# Allow "unsafe" HTML in Markdown
unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 6
  ordered = false


################################# Default parameters ##########################
[params]
logo = "images/Goonline.svg"
logo_width = "150px"
# OpenGraph / Twitter Card metadata
title = "Go Online"
description = "Providing best web solutions for business to make their online presence."
author = "Themefisher"
images = [ "images/Goonline.svg" ] # First image here will be used as fallback if a page has no images of its own


################################# Sidebar widgets #############################
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


################################# Contact page ################################
[params.contact]
# Address block
phone = "+92-321-2956633"
email = "info@goonline.dev"
location = """
**GoOnline**  
Johar Town, Lahore  
Punjab  
Pakistan
"""
# Whether to display text descriptors (like "E-mail: ", "Phone: ") before the address block elements
address_descriptors = false
[params.contact.form]
enable = true
# Whether to use [Netlify Forms](https://docs.netlify.com/forms/setup/)
use_netlify = true
# Form action
## Fill in your Form ID URL for Formspree.io, e.g. `https://formspree.io/f/{form_id}`
## Ignored if `use_netlify = true` (custom [success page](https://docs.netlify.com/forms/setup/#success-messages) is already included) 
action = "#"
# Image on custom success page `/message_sent.html`
success_image = "images/paper-plane.svg"


################################# Google map ##################################
[params.gmap]
enable = true
gmap_api = "AIzaSyCDk6wtEzuJ6DRBgfm9q3_adZue_rYarwI"
map_latitude = "31.465607449178272"
map_longitude = "74.26872231420997"
map_marker = "images/marker.png"


################################# Preloader ###################################
[params.preloader]
enable = true
preloader = "images/goonline.svg" # use .png , .svg or .gif image


################################# Cookies #####################################
[params.cookies]
enable = false
expire_days = 2


################################# Social Media ################################
[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.facebook.com/goonline.dev"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.facebook.com/goonline.dev"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.facebook.com/goonline.dev"


################################# Plugins #####################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"


################################# English translation #########################
[languages.en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
copyright = "Copyright &copy; 2021 [GoOnline](https://goonline.dev). All Rights Reserved."

# Main menu
# [[languages.en.menu.main]]
# name = "Home"
# URL = "/"
# weight = 1

[[languages.en.menu.main]]
name = "About"
URL = "about"
weight = 1

[[languages.en.menu.main]]
  name = "Services"
  URL = "service"
  weight = 2

[[languages.en.menu.main]]
name = "Projects"
URL = "project"
weight = 3

[[languages.en.menu.main]]
  name = "Pricing"
  URL = "pricing"
  weight = 4

# [[languages.en.menu.main]]
# name = "Blog"
# URL = "blog"
# weight = 6

# [[languages.en.menu.main]]
#   name = "FAQ"
#   URL = "faq"
#   weight = 7

[[languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 5

# [[languages.en.menu.main]]
# weight = 5
# name = "More"
# hasChildren = true

# Footer menu
[[languages.en.menu.footer]]
name = "About"
URL = "about"
weight = 1

[[languages.en.menu.footer]]
name = "Projects"
URL = "project"
weight = 2

[[languages.en.menu.footer]]
name = "Services"
URL = "service"
weight = 3

[[languages.en.menu.footer]]
name = "Pricing"
URL = "pricing"
weight = 4

# [[languages.en.menu.footer]]
# name = "FAQ"
# URL = "faq"
# weight = 5

[[languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 5